export const icon = {
  google: require('../assets/icons/Google.png'),
  facebook: require('../assets/icons/facebook.png'),
  mail: require('../assets/icons/mail.png'),
  lock: require('../assets/icons/padlock1.png'),
  eye: require('../assets/icons/eye.png'),
  eye_off: require('../assets/icons/closeeye.png'),
  name: require('../assets/icons/name.png'),
  telephone: require('../assets/icons/telephone.png'),
  account: require('../assets/icons/user.png'),
  account1: require('../assets/icons/user1.png'),
  drawer: require('../assets/icons/drawer.jpeg'),
  comment: require('../assets/icons/chat.png'),
  fill_save: require('../assets/icons/bookmark.png'),
  fill_heart: require('../assets/icons/filled_heart.png'),
  save: require('../assets/icons/save.png'),
  heart: require('../assets/icons/heart.png'),
  add: require('../assets/icons/add.png'),
  fill_add: require('../assets/icons/filled_add.png'),
  home: require('../assets/icons/home.png'),
  fill_home: require('../assets/icons/filled_home.png'),
  location: require('../assets/icons/placeholder.png'),
  hashtag: require('../assets/icons/hashtag.png'),
  back: require('../assets/icons/back.png'),
  mention: require('../assets/icons/mention.png'),
  logout: require('../assets/icons/logout.png'),
};
export const image = {
  splash: require('../assets/images/splash.png'),
  instagram: require('../assets/images/messenger.png'),
  post_demo: require('../assets/images/background_image.jpeg'),
  post_demo_2: require('../assets/images/vd6sHf.webp'),
  image1: require('../assets/images/image1.jpeg'),
  image2: require('../assets/images/image2.jpg'),
  image3: require('../assets/images/image3.jpeg'),
};
